server:
  port: 1003
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: navicat
    password: hb151914!@
    url: jdbc:mysql://rm-bp197o09qo91ve0zhbo.mysql.rds.aliyuncs.com:3306/seata_storage?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
  zipkin: http://localhost:9411
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
management:
  endpoints:
    web:
      exposure:
        include: '*'

## seata 配置
#seata:
#  enabled: true
#  application-id: seata-server
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  data-source-proxy-mode: AT
#  use-jdk-proxy: false
#  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  client:
#    rm:
#      async-commit-buffer-limit: 10000
#      report-retry-count: 5
#      table-meta-check-enable: false
#      report-success-enable: false
#      saga-branch-register-enable: false
#      saga-json-parser: fastjson
#      saga-retry-persist-mode-update: false
#      saga-compensate-persist-mode-update: false
#      lock:
#        retry-interval: 10
#        retry-times: 30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      commit-retry-count: 5
#      rollback-retry-count: 5
#      default-global-transaction-timeout: 60000
#      degrade-check: false
#      degrade-check-period: 2000
#      degrade-check-allow-times: 10
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#      only-care-update-columns: true
#      compress:
#        enable: true
#        type: zip
#        threshold: 64k
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default
#    grouplist:
#      default: 127.0.0.1:8091
#    enable-degrade: false
#    disable-global-transaction: false
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#      worker-thread-size: default
#      boss-thread-size: 1
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true
#  config:
#    type: file
#    nacos:
#      namespace: ""
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      username: ""
#      password: ""
#  registry:
#    type: file
#    load-balance: RandomLoadBalance
#    load-balance-virtual-nodes: 10
#    file:
#      name: file.conf
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group : "SEATA_GROUP"
#      namespace: ""
#      username: ""
#      password: ""
#  log:
mybatis:
  mapper-locations: classpath:mapper/*xml
#    exception-rate: 100