server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  profiles:
    active: dev

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp197o09qo91ve0zhbo.mysql.rds.aliyuncs.com:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: navicat
    password: hb151914!@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hebr.springboot.entites   #所有entity别名类所在的包i
logging:
  level:
    spring.hebr.springboot: debug

eureka:
  instance:
    prefer-ip-address: true
    instance-id: cloud-provider-payment8001
  client:
    fetch-registry:  true
    register-with-eureka: true
    service-url:
      defaultZone: http://com.eureka6001:6001/eureka,http://com.eureka6002:6002/eureka/
