server:
  port: 8001
spring:
  application:
    name: provider-payment8001

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp197o09qo91ve0zhbo.mysql.rds.aliyuncs.com:3306/db2021?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: navicat
    password: hb151914!@

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hebr.springboot.entites   #所有entity别名类所在的包i