server:
  port: 6001

eureka:
  instance:
    hostname: com.eureka6001 #eureka 服务端的实例名称
  client:
    #表示自己就是注册中心，不需要维护服务实例，并且不需要检索服务
    fetch-registry: false
    #表示不向注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://com.eureka6001:6001/eureka/

spring:
  application:
    name: eureka-server6001