server:
  port: 6003
spring:
  application:
    name: cloud-eureka-provider6003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6003/eureka/
    fetch-registry: false
    register-with-eureka: false